### ISSUE TITLE
wxMaxima dies (sbcl + quicklisp problem)

### ISSUE THREAD

**Issue by dprodanov** [robert-dodier/maxima-asdf#5]
When adding the quicklisp path to .sbclrc
Maxima fails to start:

wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7

**Comment by robert-dodier** [comment]
I can't tell what's going on; maybe if you post the error message it will help.

My first guess is that SBCL is not able to load Quicklisp. Someone else noted (I forget where or when) that SBCL as it is packaged with Maxima cannot load Quicklisp because Quicklisp depends on some internal functions which are not distributed with the SBCL for Maxima. I don't really know for sure.

If it's true that SBCL for Maxima cannot load Quicklisp, then there is really nothing that I can do to resolve the problem. Maybe you can obtain the necessary library or whatever and load it into SBCL and then try loading Quicklisp? But if that doesn't work then there's really nothing to do except try a different Lisp. I have used Quicklisp with Maxima compiled with Clisp and it works OK.

**Comment by robert-dodier** [comment]
I'm closing this issue since there isn't any additional information to resolve it. We can reopen it if more information is posted.
